apiVersion: v1
kind: ServiceAccount
metadata:
  name: loadtest-api
  namespace: loadtest
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: loadtest
  name: loadtest-role
rules:
- apiGroups: ["batch"]
  resources: ["jobs"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups: [""]
  resources: ["pods", "pods/log"]
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: loadtest-binding
  namespace: loadtest
subjects:
- kind: ServiceAccount
  name: loadtest-api
  namespace: loadtest
roleRef:
  kind: Role
  name: loadtest-role
  apiGroup: rbac.authorization.k8s.io